name: Lint on pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  full_ci:
    runs-on: ubuntu-18.04
    steps:
      # Get the code into the container
      - name: Checkout
        uses: actions/checkout@v2
      # Get dependencies
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v2.1.0
      ## Lint the code
      #- name: Python Linter
      #  uses: sunnysid3up/python-linter@v0.1-beta.7
      ## Lint the code part 2 - electric boogaloo
      #- name: Python Linter
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: "3.8"
      #- name: Run flake8
      #  uses: julianwachholz/flake8-action@v1.1.0
      #  with:
      #    checkName: "Python Lint"
      #    path: path/to/files
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Test the code
      - name: Test code
        run: |
          python3 tests.py

      