name: Lint on pull request
on:
  pull_request:
    branches:
      - master

jobs:
  full_ci:
    runs-on: ubuntu-18.04
    steps:
      # Get the code into the container
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
      # Make sure black is installed
      - name: Install black
        run: python3 -m pip install -U black
      # Lint the code
      - name: Lint code with black
        run: python3 -m black .
      # Test the code
      - name: Test code
        env:
          DETA_SDK_TEST_PROJECT_KEY: ${{secrets.DETA_SDK_TEST_PROJECT_KEY}}
          DETA_SDK_TEST_BASE_NAME: ${{secrets.DETA_SDK_TEST_BASE_NAME}}
        run: |
          python3 tests.py

      